-- MySQL Script generated by MySQL Workbench
-- lun 06 abr 2020 19:42:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd-hibernate-muchos-a-muchos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd-hibernate-muchos-a-muchos` ;

-- -----------------------------------------------------
-- Schema bd-hibernate-muchos-a-muchos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-hibernate-muchos-a-muchos` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE `bd-hibernate-muchos-a-muchos` ;

-- -----------------------------------------------------
-- Table `bd-hibernate-muchos-a-muchos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-hibernate-muchos-a-muchos`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `fechaDeNacimiento` DATE NULL DEFAULT NULL,
  `baja` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `cliente`
--

LOCK TABLES `cliente` WRITE;
/*!40000 ALTER TABLE `cliente` DISABLE KEYS */;
INSERT INTO `cliente` VALUES (1,'Jaramillo','Ana María',14000000,'1960-09-10','\0');
/*!40000 ALTER TABLE `cliente` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `bd-hibernate-muchos-a-muchos`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-hibernate-muchos-a-muchos`.`evento` (
  `idEvento` INT(11) NOT NULL AUTO_INCREMENT,
  `evento` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `evento`
--

LOCK TABLES `evento` WRITE;
/*!40000 ALTER TABLE `evento` DISABLE KEYS */;
INSERT INTO `evento` VALUES (1,'Evento en Luna Park','2016-01-08','21:00:00'),(2,'Gran Rex','2015-11-02','20:00:00');
/*!40000 ALTER TABLE `evento` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

-- -----------------------------------------------------
-- Table `bd-hibernate-muchos-a-muchos`.`eventoxcliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-hibernate-muchos-a-muchos`.`eventoxcliente` (
  `idEvento` INT(11) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`idEvento`, `idCliente`),
  INDEX `fk_evento_has_cliente_cliente1_idx` (`idCliente` ASC),
  INDEX `fk_evento_has_cliente_evento1_idx` (`idEvento` ASC),
  CONSTRAINT `fk_evento_has_cliente_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd-hibernate-muchos-a-muchos`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_cliente_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `bd-hibernate-muchos-a-muchos`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;
--
-- Dumping data for table `eventoxcliente`
--

LOCK TABLES `eventoxcliente` WRITE;
/*!40000 ALTER TABLE `eventoxcliente` DISABLE KEYS */;
INSERT INTO `eventoxcliente` VALUES (1,1),(2,1);
/*!40000 ALTER TABLE `eventoxcliente` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
